import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SanityLive } from "@/sanity/live";
import { ToastContainer, ToastProvider } from "@/components/contexts/Toast";
import Navbar from "@/components/organisms/Navbar/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased text-gray-800`}
      >
        <ToastProvider>
          <Navbar />
          <ToastContainer />
          {children}
          <SanityLive />
        </ToastProvider>
      </body>
    </html>
  );
}
